import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { SectionHeader } from '@/lib/ui-kit/components/SectionHeader.component'

import './globals.css'

// Font files can be colocated inside of `app`
const switzer = localFont({
  src: [
    {
      path: '../lib/ui-kit/assets/fonts/switzer/Switzer-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../lib/ui-kit/assets/fonts/switzer/Switzer-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../lib/ui-kit/assets/fonts/switzer/Switzer-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-switzer',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${switzer.variable} font-sans antialiased`}>
        <SectionHeader />
        {children}
        {/* INFO: HubSpot tracking code */}
        <script
          type="text/javascript"
          id="hs-script-loader"
          async
          defer
          src="//js.hs-scripts.com/7759219.js"
        ></script>
      </body>
    </html>
  )
}
